version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'password'
    networks:
      - postgres-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    restart: always

volumes:
  pgdata:

networks:
  postgres-network:
    driver: bridge